### ISSUE TITLE
Write QubitExpFactory run information to file for Qlab.jl

### ISSUE THREAD

**Issue by grahamrow** [BBN-Q/Auspex#127]
Save run data so that we might use an equivalent of `load_data("latest")`

**Comment by grahamrow** [comment]
Essentially a duplicate of Issue #114

**Comment by dieris** [comment]
@grahamrow I'm probably missing something, but why are the two issues the same? I thought that in this issue we wanted to create some kind of log of the most recent experiments. So that we can load e.g. the last experiment overall, the last -1 exp., the last  T1, etc... without looking through all the files.

**Comment by grahamrow** [comment]
Whoops I read the title but not the description — though this was in reference to YAML settings!

**Comment by dieris** [comment]
Closed by https://github.com/BBN-Q/Auspex/pull/137
