### ISSUE TITLE
Data axis points and original_points

### ISSUE THREAD

**Issue by dieris** [BBN-Q/Auspex#70]
`updating_descriptors` modifies `axis.points` but not `axis.original_points`. [Example](https://github.com/BBN-Q/Auspex/blob/8e24d37788b96ba017945c5cea5d2c257d20499a/src/auspex/filters/channelizer.py#L140). As a result, [`axis.num_points`](https://github.com/BBN-Q/Auspex/blob/8e24d37788b96ba017945c5cea5d2c257d20499a/src/auspex/stream.py#L78) will return the number of `original_points`, even if `points` have changed. This is relevant e.g. [here](https://github.com/BBN-Q/Auspex/blob/8e24d37788b96ba017945c5cea5d2c257d20499a/src/auspex/filters/integrator.py#L44).

As I'm not sure how this interacts with adaptive sweeps, I don't know which one to fix...

**Comment by grahamrow** [comment]
Probably update_descriptors should be responsible for setting both. The idea of `original_points` is that the axis can be reset to those original values after any sort of adaptive activity occurs. Otherwise you might have some crazily refined data points being taken in a region with no interesting behavior.

**Comment by grahamrow** [comment]
Channelizer fixed in 2b3ecbf, let me know if it's fine.

**Comment by dieris** [comment]
yes, that works, thanks!
